export const PAYPAL_CLIENT_ID = process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID
export const PAYPAL_CLIENT_SECRET = process.env.NEXT_PUBLIC_PAYPAL_CLIENT_SECRET
export const CURRENCY_CODE = process.env.NEXT_PUBLIC_PAYPAL_CURRENCY
