export const STRIPE_CLIENT_ID = process.env.NEXT_PUBLIC_STRIPE_CLIENT_ID
export const STRIPE_CLIENT_SECRET = process.env.NEXT_PUBLIC_STRIPE_CLIENT_SECRET
export const CURRENCY_CODE = process.env.NEXT_PUBLIC_STRIPE_CURRENCY
